WARNING    - 2024-02-22 14:11:38,385 - client          : PyNaCl is not installed, voice will NOT be supported
INFO       - 2024-02-22 14:11:38,387 - client          : logging in using static token
INFO       - 2024-02-22 14:11:43,467 - gateway         : Shard ID None has connected to Gateway (Session ID: 1f2d849c9853afe374098ccd4fbe1589).
ERROR      - 2024-02-22 14:12:36,367 - bot             : Ignoring exception in command sync
Traceback (most recent call last):
  File "C:\Users\Adithya\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Padhai\Code\Python\discord\Stripe-discord-bot\cogs\verify.py", line 21, in sync
    fmt = await self.bot.tree.sync(guild=ctx.guild)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Adithya\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\app_commands\tree.py", line 1072, in sync
    raise CommandSyncFailure(e, commands) from None
discord.app_commands.errors.CommandSyncFailure: Failed to upload commands to Discord (HTTP status 400, error code 50035)
In command 'update_email' defined in function 'database.update_email'
  In parameter 'OldEmail'
    name: Command name is invalid
  In parameter 'NewEmail'
    name: Command name is invalid

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Adithya\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Adithya\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Adithya\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: CommandSyncFailure: Failed to upload commands to Discord (HTTP status 400, error code 50035)
In command 'update_email' defined in function 'database.update_email'
  In parameter 'OldEmail'
    name: Command name is invalid
  In parameter 'NewEmail'
    name: Command name is invalid
